### PR TITLE
Fix/master/rsync excludes too broad

### PR DESCRIPTION
**Pull request by aaronboyle**
This will change the default behavior of sync_folders, and the documentation has been updated accordingly.

A less impactful change would have been possible by fixing rsync_includes, however that will be complicated because of the underlying behavior of rsync, and it seems in this case that the simpler option is the better design choice.

The new boolean option rsync_cvs_excludes has been added to the provider in case `--cvs-excludes` is required for someone's workflow.

### CODE REVIEW

**Comment by aaronboyle** [comment]
Closing because this is essentially a duplicate of https://github.com/ggiamarchi/vagrant-openstack-provider/pull/224

**Comment by aaronboyle** [comment]
Reopened pull request after adding boolean option rsync_cvs_excludes

**Comment by aaronboyle** [comment]
The CI failure above appears to be a toolchain problem, only present when building for vagrant 1.6.5.:

Gem::InstallError: rack requires Ruby version >= 2.2.2.
An error occurred while installing rack (2.0.1), and Bundler cannot continue.
Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.
The command "bundle _1.6.6_ install --without debug" failed. Retrying, 2 of 3.

**Comment by ggiamarchi** [comment]
@aaronboyle The provider has moved now to the standard vagrant synced folders middleware. The legacy rsync middleware within this provider is still available for now (`use_legacy_synced_folders = true`) but will be removed in a further release. By the way, the legacy implementation is no longer maintained. Thanks for your contribution.

**Pull request closed without merging**
